"""empty message

Revision ID: af233838668d
Revises: 
Create Date: 2021-10-09 13:56:30.344330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af233838668d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CVE_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_number', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CVE_info')
    # ### end Alembic commands ###
